kind: pipeline
type: docker
name: tests

platform:
  os: linux
  arch: amd64 

steps:
- name: udpate
  image: nedaya/alpine-git
  commands:
    - git remote add source https://github.com/vapor/toolbox.git
    - git pull source master
- name: test
  image: swift:5.3
  commands:
    - swift test --enable-test-discovery --sanitize=thread
---

kind: pipeline
type: docker
name: update

platform:
  os: linux
  arch: arm64 

steps:
- name: udpate
  image: nedaya/alpine-git
  commands:
    - git remote add source https://github.com/vapor/toolbox.git
    - git pull source main

- name: push commit
  image: appleboy/drone-git-push
  settings:
    remote_name: origin
    branch: master
    local_ref: main

depends_on:
- tests
---   

kind: pipeline
type: docker
name: linux-amd64

platform:
    arch: amd64 
steps:      
- name: dockerhub 
  image: plugins/docker
  settings:
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password
    repo: registry.hub.docker.com/nedaya/vapor-toolbox
    registry: registry.hub.docker.com
    auto_tag_suffix: linux-amd64
    auto_tag: true
    squash: true
    
depends_on:
- update
           
---
kind: pipeline
type: docker
name: manifest

platform:
  arch: arm64 

steps:
- name: publish
  image: plugins/manifest:1.2
  settings:
    auto_tag: true
    ignore_missing: true
    spec: docker/manifest.tmpl
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password
- name: readme
  image: nedaya/dockerhub-description:2
  environment:
    DOCKERHUB_USERNAME:
      from_secret: dockerhub_username
    DOCKERHUB_PASSWORD:
      from_secret: dockerhub_password
    DOCKERHUB_REPOSITORY: nedaya/vapor-toolbox
    README_FILEPATH: README.md
    SHORT_DESCRIPTION: "Monthly builds of vapor toolbox"
  commands:
    - node /index.js 
    
trigger:
  event:
  - push
  - tag

depends_on:
- linux-amd64
